#!/bin/bash


_ashwani_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHell
    else
        python3 -m TelethonHell
    fi
}

_starter () {
    local ashwanipath
    ashwanipath="Plugins.zip"
    echo "••• DOWNLOADING ASHWANIBOT •••"
    wget -q $(_ashwani_zip) -O "$ashwanipath"
    ASHWANIPATH=$(zipinfo -1 "$ashwanipath" | grep -v "/.");
    unzip -qq "$ashwanipath"
    rm -rf "$ashwanipath"
    cd $ASHWANIPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING ASHWANIBOT •••"
    _library
}

_starter
